name: LGTM Reaction

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  build:
    name: Send LGTM Reaction
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: micnncim/action-lgtm-reaction@master # Set some version.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
        with:
          trigger: '[".*lgtm*"]'
          override: true
          source: 'giphy'